version: '3.7'

networks:
  app_net:
    driver: bridge
volumes:
  mongodb_volume:
services:
  mongodb:
    image: 'mongo:4.2.6'
    networks:
      - app_net
    volumes:
      - mongodb_volume:/data/db
  onetimesecret:
    build: onetimesecret
    command: uvicorn app.app:app --reload --host 0.0.0.0 --port 80
    networks:
      - app_net
    ports:
      - 80:80
    environment:
      MONGO_DB_ADDR: mongodb
